# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentLsp < Formula
  desc "MCP server exposing 50+ language server protocol tools to AI agents"
  homepage "https://github.com/blackwell-systems/agent-lsp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_darwin_amd64.tar.gz"
      sha256 "662dc9cbcd6ef6e19fa01ebac7f220c69de4408da12502e0a790147b345bee92"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_darwin_arm64.tar.gz"
      sha256 "f20c55b8cc6561d736f1400722b1c4b7936653c9b5529678a439e78aae6749dc"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_linux_amd64.tar.gz"
      sha256 "c7e10f8cee01bad5cab688339d5166f5fc01ef327a0a99c6853a65e2ade41430"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_linux_arm64.tar.gz"
      sha256 "6ef2aa89bc62d1247b24d8150c22b075cf2f2b6e42a122ddc82b2715ce6bd5af"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  def caveats
    <<~EOS
      Run the setup wizard to auto-detect language servers and configure your AI tool:

        agent-lsp init

      Or manually install language servers and add to .mcp.json:

        go install golang.org/x/tools/gopls@latest
        npm install -g typescript-language-server typescript

        {
          "mcpServers": {
            "lsp": {
              "type": "stdio",
              "command": "agent-lsp",
              "args": ["go:gopls", "typescript:typescript-language-server,--stdio"]
            }
          }
        }

      Documentation: https://github.com/blackwell-systems/agent-lsp
    EOS
  end

  test do
    system "#{bin}/agent-lsp", "--version"
  end
end
