# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentLsp < Formula
  desc "MCP server exposing 50+ language server protocol tools to AI agents"
  homepage "https://github.com/blackwell-systems/agent-lsp"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.12.0/agent-lsp_darwin_amd64.tar.gz"
      sha256 "e867598bbc5d54fa631c4fbbcad61f199477a275ca12bf893f7b4041e64c2bb8"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.12.0/agent-lsp_darwin_arm64.tar.gz"
      sha256 "15391431f6feee3fb42c9489fd2ebd717229e42c0595f1e036e867e4c776b440"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.12.0/agent-lsp_linux_amd64.tar.gz"
      sha256 "5bb9b3360e35dc8abed60ad8cedc0ebd9758e18a1522306841c6b7069defa58b"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.12.0/agent-lsp_linux_arm64.tar.gz"
      sha256 "85e3146677334dc07507242184eff80763a422c7a45003dd9816cf005e3a80c2"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  def caveats
    <<~EOS
      Run the setup wizard to auto-detect language servers and configure your AI tool:

        agent-lsp init

      Or manually install language servers and add to .mcp.json:

        go install golang.org/x/tools/gopls@latest
        npm install -g typescript-language-server typescript

        {
          "mcpServers": {
            "lsp": {
              "type": "stdio",
              "command": "agent-lsp",
              "args": ["go:gopls", "typescript:typescript-language-server,--stdio"]
            }
          }
        }

      Documentation: https://github.com/blackwell-systems/agent-lsp
    EOS
  end

  test do
    system "#{bin}/agent-lsp", "--version"
  end
end
