# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentLsp < Formula
  desc "MCP server exposing 50+ language server protocol tools to AI agents"
  homepage "https://github.com/blackwell-systems/agent-lsp"
  version "0.19.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.19.2/agent-lsp_darwin_amd64.tar.gz"
      sha256 "44943ad9065c22f90376de8a1242787a3a3d0ee5c6df779bfa22b59fbeac8d6e"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.19.2/agent-lsp_darwin_arm64.tar.gz"
      sha256 "b5ae67f20e7aedc511bedee875f0a25066c0ab493d765fed53b4cc8c8d425e2e"

      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.19.2/agent-lsp_linux_amd64.tar.gz"
      sha256 "03a8cdc9a190a096d1e865154daf37d2d15fbdbc1ea0655b46ffe483e8ffeca9"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/agent-lsp/releases/download/v0.19.2/agent-lsp_linux_arm64.tar.gz"
      sha256 "325ad82236e976d4b0741167fcdbaa9125c9f4852e63fab553692a7495dc5153"
      define_method(:install) do
        bin.install "agent-lsp"
      end
    end
  end

  def caveats
    <<~EOS
      Run the setup wizard to auto-detect language servers and configure your AI tool:

        agent-lsp init

      Or manually install language servers and add to .mcp.json:

        go install golang.org/x/tools/gopls@latest
        npm install -g typescript-language-server typescript

        {
          "mcpServers": {
            "lsp": {
              "type": "stdio",
              "command": "agent-lsp",
              "args": ["go:gopls", "typescript:typescript-language-server,--stdio"]
            }
          }
        }

      Documentation: https://github.com/blackwell-systems/agent-lsp
    EOS
  end

  test do
    system "#{bin}/agent-lsp", "--version"
  end
end
