# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blackdot < Formula
  desc "Developer dotfiles and environment management CLI"
  homepage "https://github.com/blackwell-systems/blackdot"
  version "4.0.0-rc6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_x86_64.tar.gz"
      sha256 "96f9738e528750bc103c661ecec59fc415f2a7ff5de14d0cb21080981a2c389e"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_arm64.tar.gz"
      sha256 "7330ec33a53665df5352dfdfd9a59dcf72a0fd7134413c19ef7cc1fd201930ba"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_x86_64.tar.gz"
      sha256 "b4278f1aa43bf3b8a09e668d35272f8d2f641cc7511c731a4dc9d0a6f92f522c"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_arm64.tar.gz"
      sha256 "0991838227af5ec951e1be4b88abe23787f34a7c49ccd44d97d45106958e6b7c"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end
end
