# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blackdot < Formula
  desc "Developer dotfiles and environment management CLI"
  homepage "https://github.com/blackwell-systems/blackdot"
  version "4.0.0-rc6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_x86_64.tar.gz"
      sha256 "94cf17a7dfcf463bb19df341d51079fc3e32fa9db346b7a4799fde75d9d2aaf9"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_arm64.tar.gz"
      sha256 "0be31cbc3e4a5d57bd2332f83ba2c5f0aa6cc9c9aff0c827b5ca0d30147f4333"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_x86_64.tar.gz"
      sha256 "d6cd1dc7c18fc300b866b1e6c93a04bc0f405115bdbb3c1aadd1c054da2f7a37"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_arm64.tar.gz"
      sha256 "a3d6fbca5e38d27e89dfd83bc4290914741f8b4e98164fc585d37b78ce5574df"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end
end
