# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blackdot < Formula
  desc "Developer dotfiles and environment management CLI"
  homepage "https://github.com/blackwell-systems/blackdot"
  version "4.0.0-rc6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_x86_64.tar.gz"
      sha256 "6d03d2a9d4ce82fee662f87c8cea22af3481e5495df164812d0f58807ad36aa5"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Darwin_arm64.tar.gz"
      sha256 "d9760754dde0466beb13da790c1fcf018b73e4a7c50b16233377722a80b9dc08"

      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_x86_64.tar.gz"
      sha256 "f21ccb90d6530e75942ce318aa289573a34bc897553b5ca37886cd8ed284b023"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/blackdot/releases/download/v4.0.0-rc6/blackdot_4.0.0-rc6_Linux_arm64.tar.gz"
      sha256 "3c8a7a349cc17177a67e4baf0618fd2fb84047ac05ad19e8d84dde6c02adcba9"
      define_method(:install) do
        bin.install "blackdot"
      end
    end
  end
end
