# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpAssert < Formula
  desc "Deterministic correctness testing for MCP servers"
  homepage "https://github.com/blackwell-systems/mcp-assert"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.7.0/mcp-assert_0.7.0_darwin_amd64.tar.gz"
      sha256 "486f73b51d5473639e0412e38c0a6cfc301b34242ccc5a06911256240395e3d0"

      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.7.0/mcp-assert_0.7.0_darwin_arm64.tar.gz"
      sha256 "eef410b6bc4fcfdcef3752647af6acab8b942f0b84f6edc95b4e74ad09af665e"

      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.7.0/mcp-assert_0.7.0_linux_amd64.tar.gz"
      sha256 "0d3a979dd44ff349c0a585747df425f87cf3c21267a42f80b2f93731f426ce8e"
      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.7.0/mcp-assert_0.7.0_linux_arm64.tar.gz"
      sha256 "800fa346afa534a4b7fdb2f6eb864f918f2765234d3650bccfcebaa312e27a4d"
      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
  end

  test do
    assert_match "mcp-assert", shell_output("#{bin}/mcp-assert version 2>&1", 0)
  end
end
