# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpAssert < Formula
  desc "Deterministic correctness testing for MCP servers"
  homepage "https://github.com/blackwell-systems/mcp-assert"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.10.0/mcp-assert_0.10.0_darwin_amd64.tar.gz"
      sha256 "99fb1e3e7c2bed92de6e1cda80b868f6e57312916dd5500d004208d2a362ea89"

      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.10.0/mcp-assert_0.10.0_darwin_arm64.tar.gz"
      sha256 "b0f7dc748a555a84f71e2786a4f7c54c5d6db80ee657faee9f7a5ebb7d629acb"

      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.10.0/mcp-assert_0.10.0_linux_amd64.tar.gz"
      sha256 "691958e4c4c31606c1d1c8367c6acc58b9914236096a2a4c43fc1cf82336a952"
      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/mcp-assert/releases/download/v0.10.0/mcp-assert_0.10.0_linux_arm64.tar.gz"
      sha256 "80ea1024160f043d869ca242443b568a052781e61620c7ce7f705cd323d4593f"
      define_method(:install) do
        bin.install "mcp-assert"
      end
    end
  end

  test do
    assert_match "mcp-assert", shell_output("#{bin}/mcp-assert version 2>&1", 0)
  end
end
