# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeboard < Formula
  desc "Tiny cross-platform clipboard CLI with SSH + S3 sync"
  homepage "https://github.com/blackwell-systems/pipeboard"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_darwin_amd64.tar.gz"
      sha256 "ee5c0cf59aca98baa8fa769658970506c323379fd839bd1917b78751a97e90fb"

      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_darwin_arm64.tar.gz"
      sha256 "09460d877aa9f65474e478de49886acb71281aeafcfb07bb42077e51bdecd193"

      def install
        bin.install "pipeboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_linux_amd64.tar.gz"
      sha256 "8dfb2cf8edaa8643dba5dc90c740091a559dab36fa82c610f7a867cc33f47d61"
      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_linux_arm64.tar.gz"
      sha256 "82d80be69f794309749e0505897a23062f84990bbe4f0a611894a4ac28f92e97"
      def install
        bin.install "pipeboard"
      end
    end
  end

  test do
    system "#{bin}/pipeboard", "version"
  end
end
