# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeboard < Formula
  desc "Tiny cross-platform clipboard CLI with SSH + S3 sync"
  homepage "https://github.com/blackwell-systems/pipeboard"
  version "0.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.7.4/pipeboard_0.7.4_darwin_amd64.tar.gz"
      sha256 "f1c6fbd3f77729c751f7a3458ab8c9d0c8110ec22a78c962b928b3cdb1270473"

      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.7.4/pipeboard_0.7.4_darwin_arm64.tar.gz"
      sha256 "f858cb0e44608a215bf777c10e0265c0219fc7cecf89a9e653f54bf0e62d6499"

      def install
        bin.install "pipeboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.7.4/pipeboard_0.7.4_linux_amd64.tar.gz"
      sha256 "4350a0e691777450c0683506ef66a280de6c38f52c52acd0a0817634baf05538"
      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.7.4/pipeboard_0.7.4_linux_arm64.tar.gz"
      sha256 "2743c1eb3de6eea754aec1f5ed0e6f480c1f83d808061fb98722f0d8c84480e8"
      def install
        bin.install "pipeboard"
      end
    end
  end

  test do
    system "#{bin}/pipeboard", "version"
  end
end
