# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeboard < Formula
  desc "Tiny cross-platform clipboard CLI with SSH + S3 sync"
  homepage "https://github.com/blackwell-systems/pipeboard"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_darwin_amd64.tar.gz"
      sha256 "b27238c9fad398d6a7edf1410e5c89f059039e6b52fcc3d9aaa8d19a3c044f74"

      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_darwin_arm64.tar.gz"
      sha256 "82be6e014baca602054a3283ef8b18b2e7e1b65e92bd1c23aea3438cd2a58ac0"

      def install
        bin.install "pipeboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_linux_amd64.tar.gz"
      sha256 "cc1449c6c8cee843efdbdf0051ffea3b00cb345e15714b596a4fc63ec3d25029"
      def install
        bin.install "pipeboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/pipeboard/releases/download/v0.8.0/pipeboard_0.8.0_linux_arm64.tar.gz"
      sha256 "f065799587ff0bc0595d08bd508432f225c17c063107254a10aa44a53c0e9438"
      def install
        bin.install "pipeboard"
      end
    end
  end

  test do
    system "#{bin}/pipeboard", "version"
  end
end
