# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelfctl < Formula
  desc "Personal library manager for PDFs using GitHub Release assets"
  homepage "https://github.com/blackwell-systems/shelfctl"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.6/shelfctl_0.4.6_Darwin_x86_64.tar.gz"
      sha256 "3dd312b09ec0e651fad380b74f16d39539e8143a719b97521c1b5d88f79befe6"

      define_method(:install) do
        bin.install "shelfctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.6/shelfctl_0.4.6_Darwin_arm64.tar.gz"
      sha256 "6c0bdf32f0d7c21f4ffe84f8b8ad79e8edcccd4160a4000d86936f49cc19378c"

      define_method(:install) do
        bin.install "shelfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.6/shelfctl_0.4.6_Linux_x86_64.tar.gz"
      sha256 "a2a6edb1ef729feeaef2a4772dca1495ea84fcd3599d1cf1bb44c3a0cf3aa4c2"
      define_method(:install) do
        bin.install "shelfctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.6/shelfctl_0.4.6_Linux_arm64.tar.gz"
      sha256 "3e2b3e840dc2fa7685e258662b31d830c7b6ab02fa08f40c1ac4e940d2270838"
      define_method(:install) do
        bin.install "shelfctl"
      end
    end
  end
end
