# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelfctl < Formula
  desc "Personal library manager for PDFs using GitHub Release assets"
  homepage "https://github.com/blackwell-systems/shelfctl"
  version "0.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.5/shelfctl_0.4.5_Darwin_x86_64.tar.gz"
      sha256 "9ea81ee2b1017522aa3c98ca4142659c577b77e45208ae40464001d0674a3add"

      define_method(:install) do
        bin.install "shelfctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.5/shelfctl_0.4.5_Darwin_arm64.tar.gz"
      sha256 "06d0e059b05134297bce784de415151a3e67dd81849c27309eea36416c97bcac"

      define_method(:install) do
        bin.install "shelfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.5/shelfctl_0.4.5_Linux_x86_64.tar.gz"
      sha256 "85dc72e0ed1b87f5aef66409d1164a031cca18729b6771a86357a58576dd1fbb"
      define_method(:install) do
        bin.install "shelfctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackwell-systems/shelfctl/releases/download/v0.4.5/shelfctl_0.4.5_Linux_arm64.tar.gz"
      sha256 "b9193ca71c54f62713521ce14ecfaac5545fa96d8e2f25b4aa08528aae0fd43c"
      define_method(:install) do
        bin.install "shelfctl"
      end
    end
  end
end
